name: Lint

on:
  pull_request:
    branches: main

jobs:
  run-linters:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v2
  
      - name: Install ESLint
        working-directory: ./source
        run: npm install eslint-plugin-import@latest --save-dev
      
      - name: Config
        working-directory: ./source
        run: npx eslint --init
      
      - name: Run ESLint
        working-directory: ./source
        run: npx eslint "./*.js"
    
        
  
        
