name: Linting

on:
  pull_request:
    branches:
      - main
  
jobs:
  eslint:
    name: Install and run ESLint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install ESLint
        working-directory: ./source
        run: npm install eslint --save-dev
          
      - name: Set up config
        working-directory: ./source
        run: npx eslint --init
         
      - name: Run ESLint
        working-directory: ./source
        run: npx eslint "./*.js"
        
      - name: Babel
        working-directory: ./source
        run: npm install babel-cli babel-core --save-dev

        
