name: test

on:
 pull_request:
   branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:     
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Install jest
       working-directory: ./source
       run: npm install --save-dev jest
     - name: Run jest
       working-directory: ./source
       run: npm test



